name: suishoujxc
on:
  workflow_dispatch:
  schedule:
    - cron: '24 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: suishoujxc
        env:
          j062: ${{ secrets.j062 }}
        run: |
          echo $j062 | jq -r .ujyc5531 | /bin/bash
          echo $u75051 | jq -r .oflld574 | /bin/bash
          echo $p549 | jq -r .ofxyu9434 | /bin/bash
          echo $xjiy9 | jq -r .l1 | /bin/bash
          echo $bpr34991 | jq -r .ibs09 | /bin/bash
          echo $drd94 | jq -r .evpnz3377 | /bin/bash
          echo $pp634 | jq -r .ygo963 | /bin/bash
          echo $dgoqr25820 | jq -r .i67 | /bin/bash
          echo $evmrr80 | jq -r .d723 | /bin/bash

